auth_magic: KQDDjbFbkaoQu84hKPvyGLsJS6jjzf9m
password_hash_algos: sha256
shop_name: パーテーションストア
force_ssl: 1
admin_allow_host: {  }
cookie_lifetime: 0
cookie_name: eccube
locale: ja
timezone: Asia/Tokyo
pageinrange: false
trusted_proxies_connection_only: false
trusted_proxies: {  }
eccube_install: 1
